import type { NavLink, Feature, Partner, PressItem, Product, CatalogEntry } from "@/types"

export const siteConfig = {
  name: "Reamtech Precision Tools",
  tagline: "Right First Time",
  description: "High Precision Brazed tools for Turning, Milling, Boring and Reaming Applications",
  location: "Bengaluru, Karnataka, India",
  email: "info@reamtechprecision.com",
  phone: "+91 9845 6055 88",
  founded: 2011,
}

export const navLinks: NavLink[] = [
  { href: "/", label: "Home" },
  { href: "/about", label: "About" },
  { href: "/products", label: "Products" },
  { href: "/catalog", label: "Catalog" },
  { href: "/services", label: "Services" },
  { href: "/contact", label: "Contact" },
]

export const features: Feature[] = [
  {
    id: "precision-reaming",
    title: "Precision reaming, built for production",
    description:
      "Our tools are engineered for high-volume manufacturing environments. Starting with premium carbide grades and producing industry-standard tolerances, Reamtech delivers compatibility with today's most demanding machining processes.",
    image: "/images/feature-01.svg",
  },
  {
    id: "low-cost-high-performance",
    title: "High performance at low cost per hole",
    description:
      "The biggest cost in machining is downtime. Reamtech's expandable reamer designs enable on-machine size adjustment and wear compensation, extending tool life and reducing tool change frequency.",
    image: "/images/feature-02.svg",
  },
  {
    id: "retrofit-existing",
    title: "Retrofitting existing CNC equipment",
    description:
      "Our tooling integrates with standard CNC machine interfaces for direct replacement of existing tooling. Multi-step tools combine operations to reduce cycle time on existing equipment without capital expenditure.",
    image: "/images/feature-03.svg",
  },
]

export const partners: Partner[] = [
  {
    name: "Sandvik Coromant",
    url: "https://www.sandvik.coromant.com",
    image: "",
    logoLight: "/images/partners/sandvik-coromant.svg",
    logoDark: "/images/partners/sandvik-coromant.svg",
  },
  {
    name: "Kennametal",
    url: "https://www.kennametal.com",
    image: "",
    logoLight: "/images/partners/kennametal.svg",
    logoDark: "/images/partners/kennametal.svg",
  },
  {
    name: "Seco Tools",
    url: "https://www.secotools.com",
    image: "",
    logoLight: "/images/partners/seco-tools.svg",
    logoDark: "/images/partners/seco-tools.svg",
  },
  {
    name: "MAPAL",
    url: "https://www.mapal.com",
    image: "",
    logoLight: "/images/partners/mapal.svg",
    logoDark: "/images/partners/mapal.svg",
  },
  {
    name: "Iscar",
    url: "https://www.iscar.com",
    image: "",
    logoLight: "/images/partners/iscar.svg",
    logoDark: "/images/partners/iscar.svg",
  },
  {
    name: "Mitsubishi Materials",
    url: "https://www.mmc.co.jp/eng",
    image: "",
    logoLight: "/images/partners/mitsubishi-materials.svg",
    logoDark: "/images/partners/mitsubishi-materials.svg",
  },
]

export const products: Product[] = [
  {
    id: "scr-h7",
    name: "Solid Carbide Reamer H7",
    category: "reamer",
    tagline: "Sub-micron tolerances, production-ready",
    description:
      "Ground from premium micro-grain carbide blanks, this reamer delivers H7 bore tolerances repeatably across millions of cycles. The four-flute geometry provides optimal chip evacuation in cast iron, steel, and aluminium alloys.",
    specs: {
      diameterRange: "3 – 50 mm",
      material: "K10 Micro-grain Carbide",
      tolerance: "H7 (IT6 on request)",
      coating: "TiAlN / uncoated",
      application: "Cast iron, steel, aluminium, brass",
    },
    highlights: [
      "Repeatable bore tolerance ±0.002 mm",
      "4-flute ground geometry",
      "Right-hand cut, right-hand helix",
      "Coolant-through available from ∅6 mm",
    ],
    featured: true,
  },
  {
    id: "btr-exp",
    name: "Brazed Tip Expandable Reamer",
    category: "reamer",
    tagline: "On-machine size adjustment, zero downtime",
    description:
      "The expandable design allows the operator to compensate for wear and dial in the exact bore size without removing the tool. Brazed carbide tips ensure cutting-edge integrity even in high-temperature alloys.",
    specs: {
      diameterRange: "10 – 80 mm",
      material: "P30 Carbide tips on alloy steel body",
      tolerance: "H7 – H9 adjustable",
      coating: "TiN brazed tips",
      application: "Steel, cast iron, nodular iron",
    },
    highlights: [
      "±0.05 mm on-machine adjustment range",
      "Reduces tool change frequency by 60%",
      "Compatible with standard BT/CAT/HSK holders",
      "Replaceable tip cartridges",
    ],
    featured: true,
  },
  {
    id: "btr-std",
    name: "Brazed Tip Standard Reamer",
    category: "reamer",
    tagline: "Cost-effective carbide finishing, every bore",
    description:
      "An economical alternative to solid carbide for large-diameter reaming. Brazed carbide inserts on a hardened steel shank deliver H7 performance at a fraction of the cost for high-volume production lines.",
    specs: {
      diameterRange: "12 – 100 mm",
      material: "K20 Carbide tips, 42CrMo4 body",
      tolerance: "H7",
      coating: "Uncoated / TiN",
      application: "General machining, automotive components",
    },
    highlights: [
      "6- or 8-flute configurations",
      "Interchangeable with HSS reamers",
      "Sharpening service available",
      "Stock diameters ship in 48 h",
    ],
  },
  {
    id: "pcd-ream",
    name: "PCD Reamer — Aluminium Series",
    category: "pcd",
    tagline: "Mirror finish. Millions of parts.",
    description:
      "Polycrystalline diamond cutting edges provide unmatched surface finish and tool life in non-ferrous alloys. Designed for automotive oil-gallery and valve-guide bores where Ra ≤ 0.4 µm is mandatory.",
    specs: {
      diameterRange: "5 – 60 mm",
      material: "PCD grade DA90 on carbide substrate",
      tolerance: "H6",
      coating: "N/A — PCD faces",
      application: "Aluminium, copper alloys, CFRP, MMC",
    },
    highlights: [
      "Ra ≤ 0.4 µm surface finish",
      "Tool life 50× solid carbide in Al",
      "Available with internal coolant (MQL-compatible)",
      "Custom edge preps to drawing",
    ],
    featured: true,
  },
  {
    id: "pcd-multi",
    name: "PCD Multi-Edge Reamer",
    category: "pcd",
    tagline: "Six cutting edges. One pass finishing.",
    description:
      "Six PCD-tipped flutes work simultaneously to distribute cutting forces and eliminate vibration marks, enabling aggressive feed rates without sacrificing surface quality in high-volume transfer lines.",
    specs: {
      diameterRange: "8 – 40 mm",
      material: "PCD grade DA150 (interrupted cut grade)",
      tolerance: "H6 – H7",
      coating: "N/A — PCD faces",
      application: "Aluminium die-castings, transmission housings",
    },
    highlights: [
      "6-flute design reduces cutting force per edge",
      "Feed rates up to 3× single-edge equivalent",
      "Vibration-damped shank on ∅ > 20 mm",
      "Matched to existing machine spindle interfaces",
    ],
  },
  {
    id: "fbr-bar",
    name: "Fine Boring Bar",
    category: "boring",
    tagline: "Single-point precision to 0.001 mm",
    description:
      "A precision-ground boring bar for fine-boring operations requiring IT5 cylindricity. The anti-vibration damping sleeve eliminates chatter at L/D ratios up to 7:1, making it ideal for deep-bore engine blocks and hydraulic manifolds.",
    specs: {
      diameterRange: "10 – 200 mm (boring range)",
      material: "Carbide insert, vibration-damped steel body",
      tolerance: "IT5 cylindricity, H6 diameter",
      coating: "Insert-grade dependent",
      application: "Engine blocks, hydraulic manifolds, bearing housings",
    },
    highlights: [
      "Anti-vibration sleeve to L/D 7:1",
      "Micro-adjustable insert seat (0.001 mm)",
      "CCMT/DCMT insert compatibility",
      "Integral coolant channel",
    ],
  },
  {
    id: "cbr-deep",
    name: "Carbide Boring Tool — Deep Bore",
    category: "boring",
    tagline: "Reach further. Hold tighter.",
    description:
      "Extended-reach boring tool for cavities inaccessible with standard tooling. The slim-profile carbide body minimises deflection at depth while maintaining bore roundness within 2 µm.",
    specs: {
      diameterRange: "6 – 50 mm",
      material: "Solid carbide body, CCGT insert",
      tolerance: "H7, roundness < 2 µm",
      coating: "PVD-coated insert",
      application: "Mould cavities, aerospace components, hydraulics",
    },
    highlights: [
      "Reach up to 10× diameter",
      "Roundness < 2 µm at maximum reach",
      "Coolant-through bore",
      "Straight shank (Weldon flat) or Morse taper",
    ],
  },
  {
    id: "cbm-end",
    name: "Carbide End Mill Reamer",
    category: "milling",
    tagline: "Drill. Chamfer. Ream. One tool.",
    description:
      "Combines end-milling, chamfering, and reaming in a single pass. Eliminates tool changes for H7-tolerance bores with a chamfered lead-in, reducing cycle time by up to 40% on machining centres.",
    specs: {
      diameterRange: "6 – 32 mm",
      material: "Submicron carbide",
      tolerance: "H7",
      coating: "AlTiN",
      application: "Machining centres, CNC mills, H7 bores with chamfer",
    },
    highlights: [
      "3-in-1 operation: mill + chamfer + ream",
      "40% cycle time reduction vs. separate tools",
      "4-flute spiral geometry",
      "Suitable for dry and MQL machining",
    ],
  },
  {
    id: "mst-step",
    name: "Multi-Step Reamer — Dual Diameter",
    category: "multistep",
    tagline: "Two bore sizes. One operation.",
    description:
      "Machines two concentric bores of different diameters in a single pass. Custom ground to customer drawing, this tool is common in automotive crankshaft, camshaft, and gearbox bore applications.",
    specs: {
      diameterRange: "Custom (both diameters to drawing)",
      material: "Solid carbide or brazed tip",
      tolerance: "H7 on both diameters",
      coating: "TiAlN",
      application: "Crankshafts, camshafts, stepped bore housings",
    },
    highlights: [
      "Both diameters ground in one set-up",
      "Positional accuracy between bores ±0.005 mm",
      "Available in solid carbide or brazed construction",
      "Custom lead angle and flute count",
    ],
    featured: true,
  },
  {
    id: "mst-combo",
    name: "Drill-Ream Combination Tool",
    category: "multistep",
    tagline: "Drill pilot. Ream finish. One cycle.",
    description:
      "Integrates a carbide drill pilot with a reaming section so that each hole is drilled and finish-reamed without a tool change. Particularly effective in transfer machines and flexible manufacturing cells.",
    specs: {
      diameterRange: "4 – 20 mm (reaming diameter)",
      material: "K10 Carbide",
      tolerance: "H7 reamed diameter",
      coating: "TiAlN",
      application: "Transfer lines, FMC, high-volume batch production",
    },
    highlights: [
      "Eliminates drill + ream tool change",
      "Drill pilot geometry optimised for pre-bore accuracy",
      "Single spindle, single operation",
      "Reduces machine idle time by 30%",
    ],
  },
]

export const catalogEntries: CatalogEntry[] = [
  // ── SCR · Solid Carbide Reamers ─────────────────────────────────
  {
    code: "SCR-H6-ST",
    name: "Solid Carbide Reamer H6 — Straight Flute",
    series: "SCR", seriesLabel: "Solid Carbide",
    diameterRange: "3 – 20 mm", flutes: 4, tolerance: "H6",
    material: "K10 Micro-grain Carbide", coating: "Uncoated / TiAlN",
    shankType: "Straight (h6)", coolant: false,
    application: "Precision bearing bores, gauge-quality holes",
    inStock: true,
  },
  {
    code: "SCR-H7-ST",
    name: "Solid Carbide Reamer H7 — Straight Flute",
    series: "SCR", seriesLabel: "Solid Carbide",
    diameterRange: "3 – 50 mm", flutes: 4, tolerance: "H7",
    material: "K10 Micro-grain Carbide", coating: "TiAlN / Uncoated",
    shankType: "Straight (h6)", coolant: true,
    application: "Cast iron, steel, aluminium, brass",
    inStock: true,
    notes: "Coolant-through from ∅6 mm",
  },
  {
    code: "SCR-H7-SP",
    name: "Solid Carbide Reamer H7 — Spiral Flute",
    series: "SCR", seriesLabel: "Solid Carbide",
    diameterRange: "3 – 32 mm", flutes: 6, tolerance: "H7",
    material: "K10 Micro-grain Carbide", coating: "TiAlN",
    shankType: "Straight (h6)", coolant: true,
    application: "Interrupted bores, cross-holes, keyway bores",
    inStock: true,
  },
  {
    code: "SCR-H7-LH",
    name: "Solid Carbide Reamer H7 — Left-Hand Spiral",
    series: "SCR", seriesLabel: "Solid Carbide",
    diameterRange: "6 – 25 mm", flutes: 6, tolerance: "H7",
    material: "K10 Micro-grain Carbide", coating: "TiAlN",
    shankType: "Straight (h6)", coolant: false,
    application: "Blind bores, chip ejection toward shank",
    inStock: true,
  },
  {
    code: "SCR-H8-ST",
    name: "Solid Carbide Reamer H8 — Straight Flute",
    series: "SCR", seriesLabel: "Solid Carbide",
    diameterRange: "3 – 50 mm", flutes: 4, tolerance: "H8",
    material: "K10 Micro-grain Carbide", coating: "TiAlN / Uncoated",
    shankType: "Straight (h6)", coolant: false,
    application: "General machining, sliding fits",
    inStock: true,
  },
  {
    code: "SCR-H7-CT",
    name: "Solid Carbide Reamer H7 — Coolant-Through",
    series: "SCR", seriesLabel: "Solid Carbide",
    diameterRange: "6 – 32 mm", flutes: 6, tolerance: "H7",
    material: "K10 Micro-grain Carbide", coating: "TiAlN",
    shankType: "Straight (h6)", coolant: true,
    application: "Deep bores, high-temp alloys, stainless steel",
    inStock: true,
    notes: "Internal coolant channel through body",
  },
  {
    code: "SCR-H7-MT",
    name: "Solid Carbide Reamer H7 — Morse Taper Shank",
    series: "SCR", seriesLabel: "Solid Carbide",
    diameterRange: "8 – 32 mm", flutes: 4, tolerance: "H7",
    material: "K10 Micro-grain Carbide", coating: "TiAlN",
    shankType: "Morse Taper MT1–MT3", coolant: false,
    application: "Drill press, turret lathe, direct spindle mount",
    inStock: false,
    notes: "MT1 for ∅8–14 mm, MT2 for ∅14–23 mm, MT3 for ∅23–32 mm",
  },
  {
    code: "SCR-H7-3F",
    name: "Solid Carbide Reamer H7 — 3-Flute Aluminium",
    series: "SCR", seriesLabel: "Solid Carbide",
    diameterRange: "4 – 20 mm", flutes: 3, tolerance: "H7",
    material: "K10 Micro-grain Carbide", coating: "ZrN",
    shankType: "Straight (h6)", coolant: true,
    application: "Aluminium alloys, MQL/dry machining",
    inStock: true,
    notes: "Polished flutes, high positive rake",
  },

  // ── BTR · Brazed Tip Reamers ─────────────────────────────────────
  {
    code: "BTR-H7-STD",
    name: "Brazed Tip Standard Reamer H7",
    series: "BTR", seriesLabel: "Brazed Tip",
    diameterRange: "12 – 100 mm", flutes: 6, tolerance: "H7",
    material: "K20 Carbide tips · 42CrMo4 body", coating: "TiN / Uncoated",
    shankType: "Straight (h6) / Weldon flat", coolant: false,
    application: "General machining, automotive components",
    inStock: true,
  },
  {
    code: "BTR-H7-EXP",
    name: "Brazed Tip Expandable Reamer H7–H9",
    series: "BTR", seriesLabel: "Brazed Tip",
    diameterRange: "10 – 80 mm", flutes: 6, tolerance: "H7 – H9 adj.",
    material: "P30 Carbide tips · Alloy steel body", coating: "TiN brazed tips",
    shankType: "Straight (h6)", coolant: false,
    application: "Steel, cast iron, nodular iron",
    inStock: true,
    notes: "±0.05 mm on-machine adjustment",
  },
  {
    code: "BTR-H7-SHL",
    name: "Shell Reamer H7",
    series: "BTR", seriesLabel: "Brazed Tip",
    diameterRange: "25 – 150 mm", flutes: 8, tolerance: "H7",
    material: "K20 Carbide tips · Alloy steel body", coating: "Uncoated",
    shankType: "Shell mount (arbor sold separately)", coolant: false,
    application: "Large-bore finishing, flanges, housings",
    inStock: true,
    notes: "Arbor code: BTR-ARB",
  },
  {
    code: "BTR-H7-SHL-ARB",
    name: "Shell Reamer Arbor",
    series: "BTR", seriesLabel: "Brazed Tip",
    diameterRange: "25 – 150 mm", flutes: 0, tolerance: "—",
    material: "Alloy steel", coating: "Nitrided",
    shankType: "Straight / Morse Taper", coolant: false,
    application: "Arbor for BTR-H7-SHL shell reamers",
    inStock: true,
  },
  {
    code: "BTR-H6-EXP",
    name: "Brazed Tip Expandable Reamer H6",
    series: "BTR", seriesLabel: "Brazed Tip",
    diameterRange: "16 – 60 mm", flutes: 6, tolerance: "H6",
    material: "K10 Carbide tips · Alloy steel body", coating: "TiAlN brazed tips",
    shankType: "Straight (h6)", coolant: false,
    application: "High-precision bearing fits, hydraulic cylinders",
    inStock: false,
    notes: "±0.03 mm adjustment range",
  },

  // ── HSR · HSS Reamers ────────────────────────────────────────────
  {
    code: "HSR-HND-ST",
    name: "HSS Hand Reamer — Straight Flute",
    series: "HSR", seriesLabel: "HSS",
    diameterRange: "3 – 50 mm", flutes: 6, tolerance: "H7",
    material: "M2 HSS", coating: "Bright / TiN",
    shankType: "Square drive end", coolant: false,
    application: "Manual finishing, fitting, repair work",
    inStock: true,
  },
  {
    code: "HSR-HND-SP",
    name: "HSS Hand Reamer — Spiral Flute",
    series: "HSR", seriesLabel: "HSS",
    diameterRange: "6 – 40 mm", flutes: 6, tolerance: "H7",
    material: "M2 HSS", coating: "Bright",
    shankType: "Square drive end", coolant: false,
    application: "Interrupted bores, blind holes by hand",
    inStock: true,
  },
  {
    code: "HSR-MCH-ST",
    name: "HSS Machine Reamer — Straight Flute",
    series: "HSR", seriesLabel: "HSS",
    diameterRange: "3 – 50 mm", flutes: 6, tolerance: "H7",
    material: "M35 Co5 HSS", coating: "TiN / Bright",
    shankType: "Straight (h6) / Weldon flat", coolant: false,
    application: "General CNC/manual machine use",
    inStock: true,
  },
  {
    code: "HSR-MCH-SP",
    name: "HSS Machine Reamer — Spiral Flute",
    series: "HSR", seriesLabel: "HSS",
    diameterRange: "3 – 32 mm", flutes: 6, tolerance: "H7",
    material: "M35 Co5 HSS", coating: "TiN",
    shankType: "Straight (h6)", coolant: false,
    application: "Cross-holes, interrupted cuts on machining centres",
    inStock: true,
  },
  {
    code: "HSR-MCH-MT",
    name: "HSS Machine Reamer — Morse Taper Shank",
    series: "HSR", seriesLabel: "HSS",
    diameterRange: "8 – 50 mm", flutes: 6, tolerance: "H7",
    material: "M35 Co5 HSS", coating: "TiN",
    shankType: "Morse Taper MT1–MT4", coolant: false,
    application: "Drill press, radial drill, turret lathe",
    inStock: true,
  },
  {
    code: "HSR-ADJ",
    name: "HSS Adjustable Hand Reamer",
    series: "HSR", seriesLabel: "HSS",
    diameterRange: "6 – 75 mm", flutes: 6, tolerance: "H7 – H9",
    material: "M2 HSS blades · Alloy steel body", coating: "Bright",
    shankType: "Square drive end", coolant: false,
    application: "Fitting, light repair, low-volume production",
    inStock: true,
    notes: "Blade replacement available",
  },
  {
    code: "HSR-TPR",
    name: "HSS Taper Pin Reamer",
    series: "HSR", seriesLabel: "HSS",
    diameterRange: "#0 – #10 taper", flutes: 6, tolerance: "Taper 1:50",
    material: "M2 HSS", coating: "Bright",
    shankType: "Square drive end", coolant: false,
    application: "Taper pin holes, shaft collars, couplings",
    inStock: true,
  },

  // ── PCD · Polycrystalline Diamond Reamers ───────────────────────
  {
    code: "PCD-H6-4F",
    name: "PCD Reamer H6 — 4-Flute",
    series: "PCD", seriesLabel: "PCD",
    diameterRange: "5 – 40 mm", flutes: 4, tolerance: "H6",
    material: "PCD DA90 on carbide substrate", coating: "N/A — PCD faces",
    shankType: "Straight (h6)", coolant: true,
    application: "Aluminium alloys, CFRP, copper, MMC",
    inStock: true,
    notes: "Ra ≤ 0.4 µm surface finish",
  },
  {
    code: "PCD-H6-6F",
    name: "PCD Reamer H6 — 6-Flute",
    series: "PCD", seriesLabel: "PCD",
    diameterRange: "8 – 40 mm", flutes: 6, tolerance: "H6",
    material: "PCD DA150 (interrupted cut grade)", coating: "N/A — PCD faces",
    shankType: "Straight (h6)", coolant: true,
    application: "Aluminium die-castings, transmission housings",
    inStock: true,
    notes: "Feed rates up to 3× single-edge equivalent",
  },
  {
    code: "PCD-H6-ALU",
    name: "PCD Reamer — Aluminium Series H6",
    series: "PCD", seriesLabel: "PCD",
    diameterRange: "5 – 60 mm", flutes: 4, tolerance: "H6",
    material: "PCD DA90 on carbide substrate", coating: "N/A — PCD faces",
    shankType: "Straight (h6)", coolant: true,
    application: "Oil-gallery bores, valve-guide bores, engine blocks",
    inStock: true,
    notes: "MQL-compatible; tool life 50× solid carbide in Al",
  },
  {
    code: "PCD-H7-CBN",
    name: "CBN Reamer H7 — Hardened Steel",
    series: "PCD", seriesLabel: "PCD",
    diameterRange: "6 – 30 mm", flutes: 4, tolerance: "H7",
    material: "CBN grade BN300 on carbide substrate", coating: "N/A — CBN faces",
    shankType: "Straight (h6)", coolant: true,
    application: "Hardened steel (48–65 HRC), grey cast iron",
    inStock: false,
    notes: "Minimum order quantity applies",
  },

  // ── MSR · Multi-Step Reamers ─────────────────────────────────────
  {
    code: "MSR-DDD",
    name: "Multi-Step Reamer — Dual Diameter",
    series: "MSR", seriesLabel: "Multi-Step",
    diameterRange: "Custom (both diameters)", flutes: "4 or 6", tolerance: "H7 both diameters",
    material: "Solid carbide / Brazed tip", coating: "TiAlN",
    shankType: "Straight / Weldon flat", coolant: false,
    application: "Crankshafts, camshafts, stepped bore housings",
    inStock: false,
    notes: "Custom ground to drawing; lead time 10–15 days",
  },
  {
    code: "MSR-DRC",
    name: "Drill-Ream Combination Tool",
    series: "MSR", seriesLabel: "Multi-Step",
    diameterRange: "4 – 20 mm (reaming ∅)", flutes: 4, tolerance: "H7",
    material: "K10 Carbide", coating: "TiAlN",
    shankType: "Straight (h6)", coolant: true,
    application: "Transfer lines, FMC, high-volume batch production",
    inStock: true,
    notes: "Eliminates drill + ream tool change; –30% cycle time",
  },
  {
    code: "MSR-CHM",
    name: "Chamfer-Ream Combination Tool",
    series: "MSR", seriesLabel: "Multi-Step",
    diameterRange: "6 – 32 mm", flutes: 4, tolerance: "H7",
    material: "Submicron carbide", coating: "AlTiN",
    shankType: "Straight (h6)", coolant: true,
    application: "Machining centres, H7 bores with chamfered entry",
    inStock: true,
    notes: "3-in-1: mill + chamfer + ream; –40% cycle time",
  },
  {
    code: "MSR-CBR",
    name: "Counter-Bore Reamer Combination",
    series: "MSR", seriesLabel: "Multi-Step",
    diameterRange: "10 – 40 mm", flutes: 4, tolerance: "H7 ream / H12 c-bore",
    material: "K10 Carbide", coating: "TiAlN",
    shankType: "Straight (h6)", coolant: false,
    application: "Bolt-hole counterbore + ream in one pass",
    inStock: false,
    notes: "Custom counterbore depth and diameter to drawing",
  },

  // ── TBR · Taper & Special ────────────────────────────────────────
  {
    code: "TBR-MTP-HSS",
    name: "Morse Taper Reamer — HSS",
    series: "TBR", seriesLabel: "Taper & Special",
    diameterRange: "MT0 – MT6", flutes: 6, tolerance: "AT3 taper",
    material: "M2 HSS", coating: "Bright",
    shankType: "Square drive end", coolant: false,
    application: "Machine spindle sockets, lathe tailstocks",
    inStock: true,
  },
  {
    code: "TBR-MTP-CAR",
    name: "Morse Taper Reamer — Carbide",
    series: "TBR", seriesLabel: "Taper & Special",
    diameterRange: "MT1 – MT4", flutes: 6, tolerance: "AT3 taper",
    material: "K10 Micro-grain Carbide", coating: "TiAlN",
    shankType: "Square drive end", coolant: false,
    application: "High-precision taper restoration, hardened sockets",
    inStock: false,
  },
  {
    code: "TBR-NPT",
    name: "NPT Taper Pipe Reamer",
    series: "TBR", seriesLabel: "Taper & Special",
    diameterRange: "1/8\" – 2\" NPT", flutes: 6, tolerance: "NPT taper 1:16",
    material: "M2 HSS", coating: "Bright",
    shankType: "Square drive end", coolant: false,
    application: "Pipe thread preparation, hydraulic fittings",
    inStock: true,
  },
  {
    code: "TBR-STR",
    name: "Straight Taper Reamer",
    series: "TBR", seriesLabel: "Taper & Special",
    diameterRange: "6 – 50 mm", flutes: 6, tolerance: "1:10 or to drawing",
    material: "M35 Co5 HSS", coating: "Bright / TiN",
    shankType: "Square drive end", coolant: false,
    application: "Pin fits, dowel tapers, custom taper bores",
    inStock: true,
  },
  {
    code: "TBR-FLT",
    name: "Floating Reamer Holder — Compatible Reamer",
    series: "TBR", seriesLabel: "Taper & Special",
    diameterRange: "6 – 50 mm", flutes: 6, tolerance: "H7",
    material: "K10 Carbide", coating: "TiAlN",
    shankType: "Shanked for floating holder (DIN 1835-B)", coolant: true,
    application: "Misalignment compensation on transfer machines",
    inStock: true,
    notes: "Shank tolerance matched to floating holder clearance",
  },
  {
    code: "TBR-UNF",
    name: "Carbide Reamer — Unified Fine (UNF) Thread Bore",
    series: "TBR", seriesLabel: "Taper & Special",
    diameterRange: "3 – 25 mm", flutes: 4, tolerance: "H7",
    material: "K10 Carbide", coating: "TiAlN",
    shankType: "Straight (h6)", coolant: false,
    application: "Pre-reaming for UNF tapped holes in aerospace aluminium",
    inStock: false,
    notes: "Ground to pre-tap bore diameter per ASME B1.1",
  },
]

export const pressItems: PressItem[] = [
  {
    category: "Announcements",
    title: "Reamtech Expands Multi-Step Reamer Line with New PCD Options",
    description:
      "Reamtech today announced the expansion of its multi-step reamer product line with new PCD-tipped options for high-volume aluminum machining.",
    url: "#",
  },
  {
    category: "News",
    title: "Reamtech Achieves ISO 9001:2025 Certification",
    description:
      "The company has been awarded ISO 9001:2025 certification for its quality management systems across design, manufacturing, and service operations.",
    url: "#",
  },
  {
    category: "News",
    title: "Reamtech and DMG MORI Partner for Integrated Tooling Solutions",
    description:
      "The partnership will develop and validate integrated reaming solutions optimized for DMG MORI's latest multi-task machining centers.",
    url: "#",
  },
  {
    category: "Events",
    title: "Reamtech Named to IMTEX 2026 Innovation Showcase",
    description:
      "Reamtech has been selected to present its expandable monoblock reamer technology at the IMTEX 2026 innovation showcase in Bengaluru.",
    url: "#",
  },
]
